### ISSUE TITLE
Golbat does not handle Ditto with weatherboost

### ISSUE THREAD

**Issue by Fabio1988** [UnownHash/Golbat#38]
When I added logic in RDM to support the same processing as Golbat I also "fixed" the ditto with weatherboosts.

it happened that 100% Dittos were stored in DB, that's wrong when those ditto was weatherboosted 

https://github.com/RealDeviceMap/RealDeviceMap/pull/386/files#diff-7883d9d04c6a4d57b65ab97bfa4b48390a245e2fe5ce68e9719cd2d27fd2418cR1218

**Comment by Mygod** [comment]
Pro tip, Chuck supports Ditto properly. You can copy it: https://github.com/WatWowMap/Chuck/blob/master/src/models/pokemon.js

**Comment by Fabio1988** [comment]
As I copied for RDM from Chuck last time, I will also copy it to Golbat. Thank you :)

**Comment by Mygod** [comment]
Great! For real, it is worth copying the whole logic to Golbat. It also supports storing inactive IV for weather change (https://github.com/WatWowMap/Chuck/pull/57) and reset/recalc IV after weather change (https://github.com/WatWowMap/Chuck/pull/59).

**Comment by jfberry** [comment]
Changing of weather across the cell is well worthwhile; not sure about worrying about weather changing back when weather is hourly and spawntime wouldn't cross two weather changes

**Comment by Mygod** [comment]
On one hand, It's not a lot of extra efforts to do it. On the other hand, while it is true that weather typically only changes per hour, but there are certain cases when this could still be useful:

1. Weather sometimes varies per account even at the same time. For example: https://www.reddit.com/r/TheSilphRoad/comments/rx0cob/differing_spawns_and_weather_on_two_different/
If two accounts happen to be near the same area, it might clear IVs over and over again and possibly cause unnecessary scanning.
2. Spawn reroll due to event start/stop or just randomly rerolls perhaps for bugfix from Niantic. While species could change (and thus weather boost status), the set of two IVs remain.
3. Sometimes weather boosted Ditto IV scanned is different than caught. If weather changes, the scanned IV for that Ditto will become the accurate caught IV.

**Comment by jfberry** [comment]
The multi account thing is a real issue. Poracle takes a vote from monster boost status to determine definitive weather. Flip flopping is no good
Scanners are much faster now and you can argue that within a few minutes all mons will be seen and re-encountered. Perhaps changing anything proactively is expensive for no benefit. 
But this is a ditto issue and that should be fixed without doubt

**Comment by Mygod** [comment]
Well we could certainly make it configurable so that people have fewer scanners could still benefit from proactively recalculating the IVs. Either way https://github.com/WatWowMap/Chuck/pull/57 is still worth copying since it could update IV just by reseeing a mon without re-encountering it (and also for Ditto weather change).

**Comment by Mygod** [comment]
Look at this 5 minute event wow: https://pokeminers.com/sitereports/grim-omen-absol-bonus-spawns/

It would be useful to have my patch. 😏
